import { TtsVoice, TtsVoiceOption } from '../types';

export const TTS_VOICES: Record<TtsVoiceOption, TtsVoice> = {
  kore: {
    option: 'kore',
    model: 'gemini-3.8-flash-lite-tts',
    voice: 'Kore',
    gender: 'female',
    name: '코레 (Kore)',
    vibe: '다정하고 따뜻한 여사친',
    description: '차분하고 포근한 음성으로 일상을 다정하게 들어주는 친구',
    sampleText: '오늘 하루도 정말 고생 많았어. 편하게 이야기해 줘.',
    personaStyle: '차분하고 따뜻하며 공감을 잘해주는 다정한 친구 말투',
    googleStyle: true,
    shortLabel: '코레 · 여 · 다정함',
  },
  leda: {
    option: 'leda',
    model: 'gemini-3.8-flash-lite-tts',
    voice: 'Zephyr',
    gender: 'female',
    name: '레다 (Leda)',
    vibe: '밝고 통통 튀는 활기찬 여사친',
    description: '생동감 넘치고 명랑한 에너지로 기분을 북돋아 주는 친구',
    sampleText: '안녕! 오늘 무슨 재미있는 일 있었어? 완전 궁금해!',
    personaStyle: '밝고 활기차며 생동감 넘치게 맞장구쳐주는 긍정적인 말투',
    googleStyle: true,
    shortLabel: '레다 · 여 · 활기참',
  },
  zephyr: {
    option: 'zephyr',
    model: 'gemini-3.8-flash-lite-tts',
    voice: 'Zephyr',
    gender: 'female',
    name: '제피르 (Zephyr)',
    vibe: '나긋나긋하고 부드러운 톤',
    description: '부드럽고 편안한 어조로 가만히 귀 기울여 주는 친구',
    sampleText: '편안하게 생각나는 대로 천천히 이야기해 봐.',
    personaStyle: '나긋나긋하고 차분하게 경청하며 조용히 안심시켜주는 말투',
    googleStyle: true,
    shortLabel: '제피르 · 여 · 차분함',
  },
  aoede: {
    option: 'aoede',
    model: 'gemini-3.8-flash-lite-tts',
    voice: 'Kore',
    gender: 'female',
    name: '아오이데 (Aoede)',
    vibe: '세련되고 또렷한 똑순이 친구',
    description: '단정하고 이지적이며 센스 있는 대화를 나누는 친구',
    sampleText: '반가워! 오늘 어떤 흥미로운 이야기를 나눠볼까?',
    personaStyle: '단정하고 명확하며 재치 있고 센스 있는 말투',
    googleStyle: true,
    shortLabel: '아오이데 · 여 · 세련됨',
  },
  puck: {
    option: 'puck',
    model: 'gemini-3.8-flash-lite-tts',
    voice: 'Puck',
    gender: 'male',
    name: '퍽 (Puck)',
    vibe: '쾌활하고 싹싹한 남사친',
    description: '경쾌하고 맑은 톤으로 장난기 섞인 편안한 대화를 나누는 친구',
    sampleText: '어 왔냐? 오늘 밥은 잘 챙겨 먹었어? 뭐 재밌는 일 없었냐?',
    personaStyle: '장난기 있고 싹싹하며 시원시원하고 솔직한 남사친 말투',
    googleStyle: true,
    shortLabel: '퍽 · 남 · 쾌활함',
  },
  charon: {
    option: 'charon',
    model: 'gemini-3.8-flash-lite-tts',
    voice: 'Charon',
    gender: 'male',
    name: '카론 (Charon)',
    vibe: '차분하고 듬직한 중저음 남사친',
    description: '신뢰감을 주는 깊은 보이스로 든든하게 곁을 지켜주는 친구',
    sampleText: '그래, 천천히 이야기해 봐. 끝까지 다 듣고 있을게.',
    personaStyle: '차분하고 진중하며 듬직하게 힘이 되어주는 편안한 말투',
    googleStyle: true,
    shortLabel: '카론 · 남 · 중저음',
  },
  fenrir: {
    option: 'fenrir',
    model: 'gemini-3.8-flash-lite-tts',
    voice: 'Fenrir',
    gender: 'male',
    name: '펜리르 (Fenrir)',
    vibe: '따뜻하고 자신감 있는 든든한 톤',
    description: '자연스럽고 편안한 톤으로 용기와 기운을 북돋아 주는 친구',
    sampleText: '걱정 마, 넌 잘해낼 수 있어. 오늘도 힘내보자!',
    personaStyle: '자신감 있으면서도 따뜻하게 응원하고 챙겨주는 든든한 말투',
    googleStyle: true,
    shortLabel: '펜리르 · 남 · 듬직함',
  },
  // Legacy aliases
  '2': {
    option: '2',
    model: 'gemini-3.8-flash-lite-tts',
    voice: 'Puck',
    gender: 'male',
    name: '퍽 (Puck)',
    vibe: '쾌활하고 싹싹한 남사친',
    description: '경쾌하고 맑은 톤으로 장난기 섞인 편안한 대화를 나누는 친구',
    sampleText: '어 왔냐? 오늘 밥은 잘 챙겨 먹었어? 뭐 재밌는 일 없었냐?',
    personaStyle: '장난기 있고 싹싹하며 시원시원하고 솔직한 남사친 말투',
    googleStyle: true,
    shortLabel: '퍽 · 남 · 쾌활함',
  },
  '1': {
    option: '1',
    model: 'gemini-3.8-flash-lite-tts',
    voice: 'Leda',
    gender: 'female',
    name: '레다 (Leda)',
    vibe: '밝고 통통 튀는 활기찬 여사친',
    description: '생동감 넘치고 명랑한 에너지로 기분을 북돋아 주는 친구',
    sampleText: '안녕! 오늘 무슨 재미있는 일 있었어? 완전 궁금해!',
    personaStyle: '밝고 활기차며 생동감 넘치게 맞장구쳐주는 긍정적인 말투',
    googleStyle: true,
    shortLabel: '레다 · 여 · 활기참',
  },
  '7': {
    option: '7',
    model: 'gemini-3.8-flash-lite-tts',
    voice: 'Kore',
    gender: 'female',
    name: '코레 (Kore)',
    vibe: '다정하고 따뜻한 여사친',
    description: '차분하고 포근한 음성으로 일상을 다정하게 들어주는 친구',
    sampleText: '오늘 하루도 정말 고생 많았어. 편하게 이야기해 줘.',
    personaStyle: '차분하고 따뜻하며 공감을 잘해주는 다정한 친구 말투',
    googleStyle: true,
    shortLabel: '코레 · 여 · 다정함',
  },
};

export const DEFAULT_VOICE_OPTION: TtsVoiceOption = 'kore';

export function getTtsVoice(option?: string | null): TtsVoice {
  if (option && option in TTS_VOICES) {
    return TTS_VOICES[option as TtsVoiceOption];
  }
  return TTS_VOICES[DEFAULT_VOICE_OPTION];
}

export const TTS_VOICE_LIST: TtsVoice[] = [
  TTS_VOICES.kore,
  TTS_VOICES.leda,
  TTS_VOICES.zephyr,
  TTS_VOICES.aoede,
  TTS_VOICES.puck,
  TTS_VOICES.charon,
  TTS_VOICES.fenrir,
];
